CREATE TABLE IF NOT EXISTS users (
  uid int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  pswd varchar(100) NOT NULL,
  iv char(64) NOT NULL,
  phone char(11) UNIQUE,
  email char(128) UNIQUE,
  status SMALLINT DEFAULT 1 NOT NULL,
  other varchar(512) DEFAULT NULL,
  regdate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;